### ISSUE TITLE
bye

### ISSUE THREAD

**Issue by AlexHGaming** [ThreeLetters/FastBuffers#2]
bye

**Comment by segg21** [comment]
@AlexHGaming Please. Go find something better to do.

**Comment by LegitSoulja** [comment]
@AlexHGaming Banned from AJS repos, spam/ and being immature.

**Comment by AlexHGaming** [comment]
sowee daddy

**Comment by AlexHGaming** [comment]
I give a fuck because?

**Comment by Luka967** [comment]
click that button again to see a trick

**Comment by segg21** [comment]
Can you kids go elsewhere? I mean, you're not hurting us. You look dumb, you're wasting time, and being immature in general. This isn't a place for that. 

Please go find a day care.

**Comment by Andrews54757** [comment]
@LegitSoulja I gave you owner access to this org.

**Comment by Andrews54757** [comment]
@LegitSoulja I also locked the conversation. Please do not delete comments.

**Comment by Andrews54757** [comment]
I bet an employer or an admissions board would like to see this

**Comment by Andrews54757** [comment]
Also, in case this is deleted for some reason:

[hello andrewy · Issue #72 · AJS-development_OpenAgar.pdf](https://github.com/ThreeLetters/FastBuffers/files/1016390/hello.andrewy.Issue.72.AJS-development_OpenAgar.pdf)
[FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK · Issue #73 · AJS-development_OpenAgar.pdf](https://github.com/ThreeLetters/FastBuffers/files/1016391/FUCK.FUCK.FUCK.FUCK.FUCK.FUCK.FUCK.FUCK.FUCK.Issue.73.AJS-development_OpenAgar.pdf)
[bye · Issue #2 · ThreeLetters_FastBuffers.pdf](https://github.com/ThreeLetters/FastBuffers/files/1016392/bye.Issue.2.ThreeLetters_FastBuffers.pdf)

I bet an employer or an admissions board would like to see this.

> Actions have consequences

**Comment by Andrews54757** [comment]
Also, for @AlexHGaming. Please stop. I am trying to enjoy my Saturday. We have great weather right now in the northeast.
